### ISSUE TITLE
HP Device Manager Doesn't Work in Korora 21

### ISSUE THREAD

**Issue by herdkorps** [kororaproject/kp-korora-release#1]
In order to install an HP printer, I successfully installed hplip on Korora 21.  I then ran the HP Device Manager.  The Device Manager opens a window that is entirely blank except for the Window title line and controls.  I can't even get the version of HP Device Manager; the hplip version is 3.14.10-9fc21.  The program works on both Fedora 19 and Ubuntu 14.04.2 including interfacing to my printer.  

The printer is on the network and it says that it is connected to the router.  The router agrees.

**Comment by csmart** [comment]
On Korora 22 GNOME I installed hplip-gui package and ran /usr/bin/hp-toolbox and I got a working GUI. Is that what you tried?

Also, I think that once you have hplip installed, CUPS should auto-discover the printer.

**Comment by herdkorps** [comment]
More or less.  As I understand it, the the hp-toolbox of the hplip-gui package can be started from the launcher and also from the panel.  Both of these fail for me.

**Comment by csmart** [comment]
OK, I'll need to boot up a Korora 21 image, what desktop and arch are you running?

**Comment by herdkorps** [comment]
Thanks!  Using amd64 with xfce.

**Comment by jimkp** [comment]
Tested on K21 Xfce. Installed hplip-gui and the Device Manager appeared for me. It is looking for devices so I couldn't go any further but the full window appeared.

**Comment by herdkorps** [comment]
Odd.  I have tried rebooting, logging in/out, and reinstalling hplip with no joy.  Similar also is that I started by running the program with no HP devices in the beginning.

In any case, thank you very much for the effort.

**Comment by jimkp** [comment]
Personally I found hplip-gui to be a problem. I had issues controlling my Laserjet with it installed. I removed it and went back to using system-config-printer.

**Comment by herdkorps** [comment]
Another clue: the empty window cannot be removed directly by clicking the "X" in the window controls.  In that case, I get a window not responding message identifying "HP Device Manager" asking if I want to terminate the application.

It also has a second failure mode which it is doing right now.  When started from the panel, it immediately aborts, flashing the window for an instant.  When started from the launcher, it gives the empty window described earlier.

**Comment by jimkp** [comment]
Have you tried running from a terminal and looking for errors?

**Comment by herdkorps** [comment]
No, I haven't but I will because you suggest it.

On Mon, Aug 31, 2015 at 5:14 AM, jimkp notifications@github.com wrote:

> Have you tried running from a terminal and looking for errors?
> On 31 Aug 2015 7:09 pm, "herdkorps" notifications@github.com wrote:
> 
> > Another clue: the empty window cannot be removed directly by clicking the
> > "X" in the window controls. In that case, I get a window not responding
> > message identifying "HP Device Manager" asking if I want to terminate the
> > application.
> > 
> > It also has a second failure mode which it is doing right now. When
> > started from the panel, it immediately aborts, flashing the window for an
> > instant. When started from the launcher, it gives the empty window
> > described earlier.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136309095
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136309742
> .

## 

=-=-=-=
Linton Floyd

**Comment by herdkorps** [comment]
It would seem that you had a good idea there.

When I run:

which hplip-gui

I get:

/usr/bin/which: no hplip-gui in
(/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/linton/.local/bin:/home/linton/bin)

Then when I run:

sudo find / -name hplip-gui | grep -v Permission

I get nothing!  So, I cannot do as you ask.  Is there some other command
that I should be using?

On Mon, Aug 31, 2015 at 8:52 AM, Linton Floyd linton4@gmail.com wrote:

> No, I haven't but I will because you suggest it.
> 
> On Mon, Aug 31, 2015 at 5:14 AM, jimkp notifications@github.com wrote:
> 
> > Have you tried running from a terminal and looking for errors?
> > On 31 Aug 2015 7:09 pm, "herdkorps" notifications@github.com wrote:
> > 
> > > Another clue: the empty window cannot be removed directly by clicking
> > > the
> > > "X" in the window controls. In that case, I get a window not responding
> > > message identifying "HP Device Manager" asking if I want to terminate
> > > the
> > > application.
> > > 
> > > It also has a second failure mode which it is doing right now. When
> > > started from the panel, it immediately aborts, flashing the window for
> > > an
> > > instant. When started from the launcher, it gives the empty window
> > > described earlier.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136309095
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136309742
> > .
> 
> ## 
> 
> =-=-=-=
> Linton Floyd

## 

=-=-=-=
Linton Floyd

**Comment by herdkorps** [comment]
I believe that the GUI is run from python scripts but I don't know how to
make them execute.

On Mon, Aug 31, 2015 at 11:36 AM, Linton Floyd linton4@gmail.com wrote:

> It would seem that you had a good idea there.
> 
> When I run:
> 
> which hplip-gui
> 
> I get:
> 
> /usr/bin/which: no hplip-gui in
> (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/linton/.local/bin:/home/linton/bin)
> 
> Then when I run:
> 
> sudo find / -name hplip-gui | grep -v Permission
> 
> I get nothing!  So, I cannot do as you ask.  Is there some other command
> that I should be using?
> 
> On Mon, Aug 31, 2015 at 8:52 AM, Linton Floyd linton4@gmail.com wrote:
> 
> > No, I haven't but I will because you suggest it.
> > 
> > On Mon, Aug 31, 2015 at 5:14 AM, jimkp notifications@github.com wrote:
> > 
> > > Have you tried running from a terminal and looking for errors?
> > > On 31 Aug 2015 7:09 pm, "herdkorps" notifications@github.com wrote:
> > > 
> > > > Another clue: the empty window cannot be removed directly by clicking
> > > > the
> > > > "X" in the window controls. In that case, I get a window not responding
> > > > message identifying "HP Device Manager" asking if I want to terminate
> > > > the
> > > > application.
> > > > 
> > > > It also has a second failure mode which it is doing right now. When
> > > > started from the panel, it immediately aborts, flashing the window for
> > > > an
> > > > instant. When started from the launcher, it gives the empty window
> > > > described earlier.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136309095
> > > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136309742
> > > .
> > 
> > ## 
> > 
> > =-=-=-=
> > Linton Floyd
> 
> ## 
> 
> =-=-=-=
> Linton Floyd

## 

=-=-=-=
Linton Floyd

**Comment by jimkp** [comment]
Can't you just run hplip-gui?

**Comment by herdkorps** [comment]
No.  That was the point of the command:

which hplip=gui

The result would be "Command not found" meaning that there is no hplip-gui
command in the path.  I double checked this just now. Is that how you run
the GUI?

On Mon, Aug 31, 2015 at 6:21 PM, jimkp notifications@github.com wrote:

> Can't you just run hplip-gui?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136516696
> .

## 

=-=-=-=
Linton Floyd

**Comment by jimkp** [comment]
Looking at the desktop file I see the command is hp-toolbox

**Comment by herdkorps** [comment]
I just noticed something.  Here's verbatim what I get from the hplip-gui
command:

$ hplip-gui
bash: hplip-gui: command not found
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory

So there is some issue with getting the current directory in the python
scripts.

On Mon, Aug 31, 2015 at 6:41 PM, Linton Floyd linton4@gmail.com wrote:

> No.  That was the point of the command:
> 
> which hplip=gui
> 
> The result would be "Command not found" meaning that there is no
> hplip-gui command in the path.  I double checked this just now. Is that
> how you run the GUI?
> 
> On Mon, Aug 31, 2015 at 6:21 PM, jimkp notifications@github.com wrote:
> 
> > Can't you just run hplip-gui?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136516696
> > .
> 
> ## 
> 
> =-=-=-=
> Linton Floyd

## 

=-=-=-=
Linton Floyd

**Comment by herdkorps** [comment]
I get a similar thing with that too.

$ hplip-toolbox
bash: hplip-toolbox: command not found
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory

On Mon, Aug 31, 2015 at 6:51 PM, jimkp notifications@github.com wrote:

> Looking at the desktop file I see the command is hp-toolbox
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136521097
> .

## 

=-=-=-=
Linton Floyd

**Comment by csmart** [comment]
What directory are you in and can you read it?

<code bash>
pwd && ls -la
</code>

Can you paste your environment?

<code bash>
env
</code>

Or at least your path:
<code bash>
echo $PATH
</code>

**Comment by herdkorps** [comment]
OK, here goes...

[18:59] linton@captain hplip $ ``bash
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory
[22:25] linton@captain hplip $ pwd
pwd: error retrieving current directory: getcwd: cannot access parent
directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory
[22:25] linton@captain hplip $ ls -la
total 0
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory
[22:26] linton@captain hplip $ env
XDG_VTNR=1
XDG_SESSION_ID=1
SSH_AGENT_PID=1358
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/linton
HOSTNAME=captain
IMSETTINGS_INTEGRATE_DESKTOP=yes
GLADE_PIXMAP_PATH=:/usr/lib64/glade3/modules
GPG_AGENT_INFO=/home/linton/.gnupg/S.gpg-agent:1392:1
XDG_MENU_PREFIX=xfce-
SHELL=/bin/bash
TERM=xterm-256color
HISTSIZE=1000
WINDOWID=25165880
QTDIR=/usr/lib64/qt-3.3
GNOME_KEYRING_CONTROL=/home/linton/.cache/keyring-ES6C4X
QTINC=/usr/lib64/qt-3.3/include
QT_GRAPHICSSYSTEM_CHECKED=1
IMSETTINGS_MODULE=none
USER=linton
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:_.tar=38;5;9:_.tgz=38;5;9:_.arc=38;5;9:_.arj=38;5;9:_.taz=38;5;9:_.lha=38;5;9:_.lz4=38;5;9:_.lzh=38;5;9:_.lzma=38;5;9:_.tlz=38;5;9:_.txz=38;5;9:_.tzo=38;5;9:_.t7z=38;5;9:_.zip=38;5;9:_.z=38;5;9:_.Z=38;5;9:_.dz=38;5;9:_.gz=38;5;9:_.lrz=38;5;9:_.lz=38;5;9:_.lzo=38;5;9:_.xz=38;5;9:_.bz2=38;5;9:_.bz=38;5;9:_.tbz=38;5;9:_.tbz2=38;5;9:_.tz=38;5;9:_.deb=38;5;9:_.rpm=38;5;9:_.jar=38;5;9:_.war=38;5;9:_.ear=38;5;9:_.sar=38;5;9:_.rar=38;5;9:_.alz=38;5;9:_.ace=38;5;9:_.zoo=38;5;9:_.cpio=38;5;9:_.7z=38;5;9:_.rz=38;5;9:_.cab=38;5;9:_.jpg=38;5;13:_.jpeg=38;5;13:_.gif=38;5;13:_.bmp=38;5;13:_.pbm=38;5;13:_.pgm=38;5;13:_.ppm=38;5;13:_.tga=38;5;13:_.xbm=38;5;13:_.xpm=38;5;13:_.tif=38;5;13:_.tiff=38;5;13:_.png=38;5;13:_.svg=38;5;13:_.svgz=38;5;13:_.mng=38;5;13:_.pcx=38;5;13:_.mov=38;5;13:_.mpg=38;5;13:_.mpeg=38;5;13:_.m2v=38;5;13:_.mkv=38;5;13:_.webm=38;5;13:_.ogm=38;5;13:_.mp4=38;5;13:_.m4v=38;5;13:_.mp4v=38;5;13:_.vob=38;5;13:_.qt=38;5;13:_.nuv=38;5;13:_.wmv=38;5;13:_.asf=38;5;13:_.rm=38;5;13:_.rmvb=38;5;13:_.flc=38;5;13:_.avi=38;5;13:_.fli=38;5;13:_.flv=38;5;13:_.gl=38;5;13:_.dl=38;5;13:_.xcf=38;5;13:_.xwd=38;5;13:_.yuv=38;5;13:_.cgm=38;5;13:_.emf=38;5;13:_.ogv=38;5;13:_.ogx=38;5;13:_.aac=38;5;45:_.au=38;5;45:_.flac=38;5;45:_.m4a=38;5;45:_.mid=38;5;45:_.midi=38;5;45:_.mka=38;5;45:_.mp3=38;5;45:_.mpc=38;5;45:_.ogg=38;5;45:_.ra=38;5;45:_.wav=38;5;45:_.oga=38;5;45:_.opus=38;5;45:_.spx=38;5;45:_.xspf=38;5;45:
GLADE_MODULE_PATH=:/usr/share/glade3/pixmaps
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/tmp/ssh-OFJcq6OnQFOW/agent.1229
SESSION_MANAGER=local/unix:@
/tmp/.ICE-unix/1388,unix/unix:/tmp/.ICE-unix/1388
XDG_CONFIG_DIRS=/etc/xdg
DESKTOP_SESSION=xfce
MAIL=/var/spool/mail/linton
PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/linton/.local/bin:/home/linton/bin
QT_IM_MODULE=xim
PWD=/usr/share/hplip
XMODIFIERS=@im=none
KDE_IS_PRELINKED=1
LANG=en_US.utf8
KDEDIRS=/usr
PS1=[\033[0;34m][$(date +%H:%M)]
[\033[0;32m]\u[\033[0;36m]@[\033[0;32m]\h[\033[0;34m]
\W[\033[0;32m]$(parse-git-branch.sh) [\033[0;34m]$[\033[00m]
GDMSESSION=xfce
HISTCONTROL=ignoredups
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
SHLVL=4
HOME=/home/linton
XDG_SEAT=seat0
GDL_PATH=+/usr/share/gnudatalanguage
LOGNAME=linton
QTLIB=/usr/lib64/qt-3.3/lib
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-aDNo1I72d9,guid=749c51a10426f4dd56b7bd6c55e2270b
XDG_DATA_DIRS=/usr/local/share:/usr/share
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0.0
GLADE_CATALOG_PATH=:/usr/share/glade3/catalogs
XAUTHORITY=/var/run/lightdm/linton/xauthority
COLORTERM=xfce4-terminal
_=/usr/bin/env
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory
[22:26] linton@captain hplip $ grep linton /etc/passwd
linton:x:1000:1000:Linton Floyd:/home/linton:/bin/bash
shell-init: error retrieving current directory: getcwd: cannot access
parent directories: No such file or directory
[22:27] linton@captain hplip $ echo $HOME
/home/linton

On Mon, Aug 31, 2015 at 8:58 PM, Chris Smart notifications@github.com
wrote:

> What directory are you in and can you read it?
> 
> ``bash
> pwd && ls -la
> 
> Can you paste your environment?
> 
> ``` bash
> env
> 
> Or at least your path:
> 
> echo $PATH
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136540325>
> .
> 
> 
> 
> ```

## 

=-=-=-=
Linton Floyd

**Comment by herdkorps** [comment]
I've fixed the problem.  I will send a full description after I complete it.

Thanks!!!

On Mon, Aug 31, 2015 at 8:58 PM, Chris Smart notifications@github.com
wrote:

> What directory are you in and can you read it?
> 
> ``bash
> pwd && ls -la
> 
> Can you paste your environment?
> 
> ``` bash
> env
> 
> Or at least your path:
> 
> echo $PATH
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136540325>
> .
> 
> 
> 
> ```

## 

=-=-=-=
Linton Floyd

**Comment by herdkorps** [comment]
I needed to figure out what command to enter to run the desired python
script.  So, I got ran the applet to get the dreaded blank window.  Then,

ps -aux | grep "hp-"

linton   17521  1.0  1.6 664740 79220 ?        S    09:33   0:00
/usr/bin/python /usr/bin/hp-toolbox

Perhaps I need to run as superuser.

[09:36] linton@captain ~ $ sudo /usr/bin/python /usr/bin/hp-toolbox
warning: hp-toolbox should not be run as root/superuser.

HP Linux Imaging and Printing System (ver. 3.14.10)
HP Device Manager ver. 15.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

\error: dBus initialization error. Exiting.

OK, if you say so.

[09:37] linton@captain ~ $ /usr/bin/python /usr/bin/hp-toolbox

HP Linux Imaging and Printing System (ver. 3.14.10)
HP Device Manager ver. 15.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

\
HP Linux Imaging and Printing System (ver. 3.14.10)
System Tray Status Service ver. 2.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

error: Unable to open /home/linton/.hplip/hp-systray.lock lock file.
warning: Unable to connect to dbus. Is hp-systray running?
error: dBus initialization error. Exiting.
Segmentation fault (core dumped)

LOL!!!  I haven't stimulated a core dump in years!  Congratulate me.
Anyway, there is a lock file to be dealt with.

[09:37] linton@captain ~ $ ll /home/linton/.hplip/hp-systray.lock
-r--r--r--. 1 linton linton 0 Oct  6  2014
/home/linton/.hplip/hp-systray.lock
[09:43] linton@captain ~ $ rm !$
rm /home/linton/.hplip/hp-systray.lock
rm: remove write-protected regular empty file
‘/home/linton/.hplip/hp-systray.lock’? y
[09:44] linton@captain ~ $ /usr/bin/python /usr/bin/hp-toolbox

HP Linux Imaging and Printing System (ver. 3.14.10)
HP Device Manager ver. 15.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

\
HP Linux Imaging and Printing System (ver. 3.14.10)
System Tray Status Service ver. 2.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127:
RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)

From here, I was able to connect to the printer via the GUI although I had
to use root privilege where I shouldn't have needed to.

Thank you again for all of your help.

Linton

On Mon, Aug 31, 2015 at 10:30 PM, Linton Floyd linton4@gmail.com wrote:

> OK, here goes...
> 
> [18:59] linton@captain hplip $ ``bash
> shell-init: error retrieving current directory: getcwd: cannot access
> parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access
> parent directories: No such file or directory
> [22:25] linton@captain hplip $ pwd
> pwd: error retrieving current directory: getcwd: cannot access parent
> directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access
> parent directories: No such file or directory
> [22:25] linton@captain hplip $ ls -la
> total 0
> shell-init: error retrieving current directory: getcwd: cannot access
> parent directories: No such file or directory
> [22:26] linton@captain hplip $ env
> XDG_VTNR=1
> XDG_SESSION_ID=1
> SSH_AGENT_PID=1358
> XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/linton
> HOSTNAME=captain
> IMSETTINGS_INTEGRATE_DESKTOP=yes
> GLADE_PIXMAP_PATH=:/usr/lib64/glade3/modules
> GPG_AGENT_INFO=/home/linton/.gnupg/S.gpg-agent:1392:1
> XDG_MENU_PREFIX=xfce-
> SHELL=/bin/bash
> TERM=xterm-256color
> HISTSIZE=1000
> WINDOWID=25165880
> QTDIR=/usr/lib64/qt-3.3
> GNOME_KEYRING_CONTROL=/home/linton/.cache/keyring-ES6C4X
> QTINC=/usr/lib64/qt-3.3/include
> QT_GRAPHICSSYSTEM_CHECKED=1
> IMSETTINGS_MODULE=none
> USER=linton
> 
> LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:_.tar=38;5;9:_.tgz=38;5;9:_.arc=38;5;9:_.arj=38;5;9:_.taz=38;5;9:_.lha=38;5;9:_.lz4=38;5;9:_.lzh=38;5;9:_.lzma=38;5;9:_.tlz=38;5;9:_.txz=38;5;9:_.tzo=38;5;9:_.t7z=38;5;9:_.zip=38;5;9:_.z=38;5;9:_.Z=38;5;9:_.dz=38;5;9:_.gz=38;5;9:_.lrz=38;5;9:_.lz=38;5;9:_.lzo=38;5;9:_.xz=38;5;9:_.bz2=38;5;9:_.bz=38;5;9:_.tbz=38;5;9:_.tbz2=38;5;9:_.tz=38;5;9:_.deb=38;5;9:_.rpm=38;5;9:_.jar=38;5;9:_.war=38;5;9:_.ear=38;5;9:_.sar=38;5;9:_.rar=38;5;9:_.alz=38;5;9:_.ace=38;5;9:_.zoo=38;5;9:_.cpio=38;5;9:_.7z=38;5;9:_.rz=38;5;9:_.cab=38;5;9:_.jpg=38;5;13:_.jpeg=38;5;13:_.gif=38;5;13:_.bmp=38;5;13:_.pbm=38;5;13:_.pgm=38;5;13:_.ppm=38;5;13:_.tga=38;5;13:_.xbm=38;5;13:_.xpm=38;5;13:_.tif=38;5;13:_.tiff=38;5;13:_.png=38;5;13:_.svg=38;5;13:_.svgz=38;5;13:_.mng=38;5;13:_.pcx=38;5;13:_.mov=38;5;13:_.mpg=38;5;13:_.mpeg=38;5;13:_.m2v=38;5;13:_.mkv=38;5;13:_.webm=38;5;13:_.ogm=38;5;13:_.mp4=38;5;13:_.m4v=38;5;13:_.mp4v=38;5;13:_.vob=38;5;13:_.qt=38;5;13:_.nuv=38;5;13:_.wmv=38;5;13:_.asf=38;5;13:_.rm=38;5;13:_.rmvb=38;5;13:_.flc=38;5;13:_.avi=38;5;13:_.fli=38;5;13:_.flv=38;5;13:_.gl=38;5;13:_.dl=38;5;13:_.xcf=38;5;13:_.xwd=38;5;13:_.yuv=38;5;13:_.cgm=38;5;13:_.emf=38;5;13:_.ogv=38;5;13:_.ogx=38;5;13:_.aac=38;5;45:_.au=38;5;45:_.flac=38;5;45:_.m4a=38;5;45:_.mid=38;5;45:_.midi=38;5;45:_.mka=38;5;45:_.mp3=38;5;45:_.mpc=38;5;45:_.ogg=38;5;45:_.ra=38;5;45:_.wav=38;5;45:_.oga=38;5;45:_.opus=38;5;45:_.spx=38;5;45:_.xspf=38;5;45:
> GLADE_MODULE_PATH=:/usr/share/glade3/pixmaps
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
> XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
> SSH_AUTH_SOCK=/tmp/ssh-OFJcq6OnQFOW/agent.1229
> SESSION_MANAGER=local/unix:@
> /tmp/.ICE-unix/1388,unix/unix:/tmp/.ICE-unix/1388
> XDG_CONFIG_DIRS=/etc/xdg
> DESKTOP_SESSION=xfce
> MAIL=/var/spool/mail/linton
> 
> PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/linton/.local/bin:/home/linton/bin
> QT_IM_MODULE=xim
> PWD=/usr/share/hplip
> XMODIFIERS=@im=none
> KDE_IS_PRELINKED=1
> LANG=en_US.utf8
> KDEDIRS=/usr
> PS1=[\033[0;34m][$(date +%H:%M)]
> [\033[0;32m]\u[\033[0;36m]@[\033[0;32m]\h[\033[0;34m]
> \W[\033[0;32m]$(parse-git-branch.sh) [\033[0;34m]$[\033[00m]
> GDMSESSION=xfce
> HISTCONTROL=ignoredups
> SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
> SHLVL=4
> HOME=/home/linton
> XDG_SEAT=seat0
> GDL_PATH=+/usr/share/gnudatalanguage
> LOGNAME=linton
> QTLIB=/usr/lib64/qt-3.3/lib
> 
> DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-aDNo1I72d9,guid=749c51a10426f4dd56b7bd6c55e2270b
> XDG_DATA_DIRS=/usr/local/share:/usr/share
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/1000
> DISPLAY=:0.0
> GLADE_CATALOG_PATH=:/usr/share/glade3/catalogs
> XAUTHORITY=/var/run/lightdm/linton/xauthority
> COLORTERM=xfce4-terminal
> _=/usr/bin/env
> shell-init: error retrieving current directory: getcwd: cannot access
> parent directories: No such file or directory
> [22:26] linton@captain hplip $ grep linton /etc/passwd
> linton:x:1000:1000:Linton Floyd:/home/linton:/bin/bash
> shell-init: error retrieving current directory: getcwd: cannot access
> parent directories: No such file or directory
> [22:27] linton@captain hplip $ echo $HOME
> /home/linton
> 
> On Mon, Aug 31, 2015 at 8:58 PM, Chris Smart notifications@github.com
> wrote:
> 
> > What directory are you in and can you read it?
> > 
> > ``bash
> > pwd && ls -la
> > 
> > Can you paste your environment?
> > 
> > ``` bash
> > env
> > 
> > Or at least your path:
> > 
> > echo $PATH
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136540325>
> > .
> > 
> > 
> > 
> > ```
> 
> ## 
> 
> =-=-=-=
> Linton Floyd

## 

=-=-=-=
Linton Floyd

**Comment by csmart** [comment]
OK, glad you got it sorted although it's strange that you had to use sudo. I wasn't able to reproduce it so not sure there's anything we can do here to fix it. If anyone else has the same problem we can re-look at it.

**Comment by herdkorps** [comment]
Thanks again for the help you provided.

I think that running the program from the launcher and then the pallet may
have caused the problem.  (I was not aware at the time that a window had
actually been launched.)  This could have caused the spurious lock file.

As for the unusual need for permission escalation, this was not the first
time in this young installation.  During initial updating, one of the
packages (which one I don't recall right now) required that I import and
run a rpm version directly.  Thereafter for several days, I could not
update the system unless as root.  Oddly and thankfully, this behavior
ceased after about a week and no other anomalies other than the hplip one
have occurred.

On Wed, Sep 2, 2015 at 12:03 AM, Chris Smart notifications@github.com
wrote:

> OK, glad you got it sorted although it's strange that you had to use sudo.
> I wasn't able to reproduce it so not sure there's anything we can do here
> to fix it. If anyone else has the same problem we can re-look at it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kororaproject/kp-korora-release/issues/1#issuecomment-136932407
> .

## 

=-=-=-=
Linton Floyd

**Comment by herdkorps** [comment]
With lots of help from jimkp and Chris Smart, the problem is now solved.  It probably was not a problem with the distribution but rather how the software reacts in nonstandard usage.  Let me explain

When running the GUI from the command line, I noticed something.  Here's verbatim what I get from the hplip-gui command:

$ hplip-gui
bash: hplip-gui: command not found
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

So,  there was some issue with getting the current directory in the python scripts.  So, I needed to figure out what command to enter to run the desired python script.  I ran the applet to get the dreaded blank window.  Then,

ps -aux | grep "hp-"

linton   17521  1.0  1.6 664740 79220 ?        S    09:33   0:00 /usr/bin/python /usr/bin/hp-toolbox

So, I kill the window using  the window controls and enter:

$ /usr/bin/python /usr/bin/hp-toolbox

HP Linux Imaging and Printing System (ver. 3.14.10)
HP Device Manager ver. 15.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

\
HP Linux Imaging and Printing System (ver. 3.14.10)
System Tray Status Service ver. 2.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

error: Unable to open /home/linton/.hplip/hp-systray.lock lock file.
warning: Unable to connect to dbus. Is hp-systray running?
error: dBus initialization error. Exiting.
Segmentation fault (core dumped)

LOL!!!  I haven't stimulated Linux/Unix a core dump in years!  Congratulate me.  Anyway, there was a lock file to be dealt with.

(Also, please forgive the HP application's loquaciousness.

$ ll /home/linton/.hplip/hp-systray.lock
-r--r--r--. 1 linton linton 0 Oct  6  2014 /home/linton/.hplip/hp-systray.lock
$ rm !$
rm /home/linton/.hplip/hp-systray.lock
rm: remove write-protected regular empty file ‘/home/linton/.hplip/hp-systray.lock’? y
$ /usr/bin/python /usr/bin/hp-toolbox

HP Linux Imaging and Printing System (ver. 3.14.10)
HP Device Manager ver. 15.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

\
HP Linux Imaging and Printing System (ver. 3.14.10)
System Tray Status Service ver. 2.0

Copyright (c) 2001-13 Hewlett-Packard Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)

From here, I was able to connect to the printer via the GUI although I had to use root privilege where I shouldn't have needed to.

I still do not know why the lock file was there.  Perhaps it happened when I started the hplip-gui from the panel when it was already running from the launcher.  I don't know.
